/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Recipe
         * @description Start extraction from a link or pasted text. Poll the returned job.
         */
        post: operations["create_recipe_api_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["get_recipe_api_recipes__recipe_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Recipe */
        post: operations["plan_recipe_api_recipes__recipe_id__plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Costs */
        Costs: {
            /** Trip Total */
            trip_total: number;
            /** Per Meal */
            per_meal: number;
            /**
             * Currency
             * @default USD
             * @constant
             */
            currency: "USD";
            /**
             * Approximate
             * @default true
             * @constant
             */
            approximate: true;
        };
        /**
         * CreateRecipeRequest
         * @description Start extraction from a link, or from pasted caption/ingredient text.
         */
        CreateRecipeRequest: {
            /** Url */
            url?: string | null;
            /** Text */
            text?: string | null;
        };
        /** GroceryItem */
        GroceryItem: {
            /** Ingredient Id */
            ingredient_id: string;
            /** Name */
            name: string;
            product: components["schemas"]["Product"];
            /**
             * Packages
             * @description How many packages to buy
             */
            packages: number;
            /**
             * Line Total
             * @description packages x package_price
             */
            line_total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Ingredient */
        Ingredient: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity?: number | null;
            /** Unit */
            unit?: string | null;
            /** Grams */
            grams?: number | null;
            /** Estimated */
            estimated: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "caption" | "transcript" | "frames" | "pasted" | "inferred";
            /** Confidence */
            confidence: number;
            /**
             * Owned
             * @default false
             */
            owned: boolean;
            product?: components["schemas"]["Product"] | null;
            /** Fdc Id */
            fdc_id?: number | null;
        };
        /** Job */
        Job: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Stages
             * @description Stages this job plans to run, in order
             */
            stages: components["schemas"]["Stage"][];
            /** @description Stage running now, or the one that failed */
            stage: components["schemas"]["Stage"] | null;
            /** Completed Stages */
            completed_stages: components["schemas"]["Stage"][];
            /** Recipe Id */
            recipe_id?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "running" | "done" | "failed";
        /** Macros */
        Macros: {
            /** Calories */
            calories: number;
            /** Protein G */
            protein_g: number;
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
            /** Approximate */
            approximate: boolean;
        };
        /**
         * MealPlan
         * @description Output of planning: the full results page for one recipe.
         */
        MealPlan: {
            /** Recipe Id */
            recipe_id: string;
            /** Source Url */
            source_url: string | null;
            /** Title */
            title: string;
            /** Zip Code */
            zip_code: string;
            servings: components["schemas"]["Servings"];
            /** Ingredients */
            ingredients: components["schemas"]["Ingredient"][];
            /** Grocery List */
            grocery_list: components["schemas"]["GroceryItem"][];
            /** Steps */
            steps: components["schemas"]["Step"][];
            costs: components["schemas"]["Costs"];
            macros_per_serving: components["schemas"]["Macros"];
        };
        /** PlanRequest */
        PlanRequest: {
            /** Zip Code */
            zip_code: string;
            /**
             * Owned Ingredient Ids
             * @default []
             */
            owned_ingredient_ids: string[];
        };
        /** Product */
        Product: {
            /** Store Id */
            store_id: string;
            /** Store Name */
            store_name: string;
            /** Product Name */
            product_name: string;
            /** Package Size Grams */
            package_size_grams: number;
            /** Package Price */
            package_price: number;
            /**
             * Price Type
             * @enum {string}
             */
            price_type: "store price" | "estimate";
        };
        /**
         * Recipe
         * @description Output of extraction: what the reel says to cook.
         */
        Recipe: {
            /** Id */
            id: string;
            /** Source Url */
            source_url: string | null;
            /** Title */
            title: string;
            /** Creator */
            creator?: string | null;
            servings: components["schemas"]["Servings"];
            /** Ingredients */
            ingredients: components["schemas"]["Ingredient"][];
        };
        /** Servings */
        Servings: {
            /** Value */
            value: number;
            /** Estimated */
            estimated: boolean;
        };
        /**
         * Stage
         * @description Extraction stages, in the order they run.
         * @enum {string}
         */
        Stage: "metadata" | "audio" | "frames" | "merge";
        /** Step */
        Step: {
            /** Order */
            order: number;
            /** Instruction */
            instruction: string;
            /** Timer Seconds */
            timer_seconds?: number | null;
            /** Doneness Cue */
            doneness_cue?: string | null;
            /** Safety Note */
            safety_note?: string | null;
            /** Equipment Swap */
            equipment_swap?: string | null;
            /**
             * Terms
             * @default []
             */
            terms: components["schemas"]["Term"][];
            /** Video Start Seconds */
            video_start_seconds?: number | null;
            /** Video End Seconds */
            video_end_seconds?: number | null;
        };
        /** Term */
        Term: {
            /** Term */
            term: string;
            /** Definition */
            definition: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_recipe_api_recipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecipeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_api_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_recipe_api_recipes__recipe_id__plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
