// Thin typed client for the FastAPI backend. Types come from
// src/lib/api-types.ts, generated by `npm run gen:api` — don't edit that file.
import type { components } from "./api-types";

type Schemas = components["schemas"];
export type Job = Schemas["Job"];
export type Stage = Schemas["Stage"];
export type Recipe = Schemas["Recipe"];
export type Ingredient = Schemas["Ingredient"];
export type MealPlan = Schemas["MealPlan"];
export type GroceryItem = Schemas["GroceryItem"];
export type Step = Schemas["Step"];
export type CreateRecipeRequest = Schemas["CreateRecipeRequest"];
export type PlanRequest = Schemas["PlanRequest"];

// Same-origin path; next.config.ts forwards /api/* to the backend.
const API_URL = "/api";

export class ApiError extends Error {
  constructor(
    message: string,
    readonly status: number,
  ) {
    super(message);
  }
}

// FastAPI returns `detail` as a string for our own errors, or as a list of
// validation errors from Pydantic.
function errorMessage(body: unknown): string {
  const detail = (body as { detail?: unknown })?.detail;
  if (typeof detail === "string") return detail;
  if (Array.isArray(detail) && detail[0]?.msg) {
    return String(detail[0].msg).replace(/^Value error, /, "");
  }
  return "Something went wrong. Please try again.";
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  let res: Response;
  try {
    res = await fetch(`${API_URL}${path}`, {
      ...init,
      headers: { "Content-Type": "application/json", ...init?.headers },
    });
  } catch {
    throw new ApiError("Can't reach Breaking Bread right now. Is the backend running?", 0);
  }
  const body = await res.json().catch(() => null);
  // A non-JSON 5xx means the /api forwarding couldn't reach the backend.
  if (res.status >= 500 && body === null) {
    throw new ApiError("Can't reach Breaking Bread right now. Is the backend running?", res.status);
  }
  if (!res.ok) throw new ApiError(errorMessage(body), res.status);
  return body as T;
}

export const api = {
  createRecipe: (body: CreateRecipeRequest) =>
    request<Job>("/recipes", { method: "POST", body: JSON.stringify(body) }),
  getJob: (jobId: string) => request<Job>(`/jobs/${encodeURIComponent(jobId)}`),
  getRecipe: (recipeId: string) => request<Recipe>(`/recipes/${encodeURIComponent(recipeId)}`),
  planRecipe: (recipeId: string, body: PlanRequest) =>
    request<MealPlan>(`/recipes/${encodeURIComponent(recipeId)}/plan`, {
      method: "POST",
      body: JSON.stringify(body),
    }),
};
